Update botssh

diff --git a/Modulos/botssh b/Modulos/botssh
--- a/Modulos/botssh
+++ b/Modulos/botssh
@@ -35,7 +35,7 @@ fun_botOnOff () {
   	    echo ""
   	    echo -ne "\033[1;32mINFORM YOUR ID:\033[1;37m "; read iduser
           clear
-          echo -e "\033[1;32mSTARTING DARKSSH BOT \033[0m\n"
+          echo -e "\033[1;32mSTARTING SDSSH BOT \033[0m\n"
           fun_bot1 () {
   	        [[ ! -e "/etc/DARKssh/ShellBot.sh" ]] && wget -qO- https://raw.githubusercontent.com/shellscriptx/shellbot/master/ShellBot.sh > /etc/DARKssh/ShellBot.sh
   	        cd /etc/DARKssh
@@ -50,12 +50,12 @@ fun_botOnOff () {
   	        cd $HOME
           }
           fun_bar 'fun_bot1'
-          [[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m DARKSSH BOT ON !\033[0m" || echo -e "\n\033[1;31m ERROR! RE-ANALYZE YOUR INFORMATION\033[0m"
+          [[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m SDSSH BOT ON !\033[0m" || echo -e "\n\033[1;31m ERROR! RE-ANALYZE YOUR INFORMATION\033[0m"
           sleep 3
           menu
       } || {
           clear
-          echo -e "\033[1;32mSTOPPING BOT DARKSSH ... \033[0m\n"
+          echo -e "\033[1;32mSTOPPING BOT SDSSH ... \033[0m\n"
           fun_bot2 () {
               screen -r -S "bot_plus" -X quit
               screen -wipe 1>/dev/null 2>/dev/null
@@ -66,14 +66,14 @@ fun_botOnOff () {
               sleep 1
           }
           fun_bar 'fun_bot2'
-          echo -e "\n\033[1;32m \033[1;31mDARKSSH BOT STOPPED! \033[0m"
+          echo -e "\n\033[1;32m \033[1;31mSDSSH BOT STOPPED! \033[0m"
           sleep 3
           menu
       }
 }
 
 fun_instbot () {
-echo -e "\E[44;1;37m             BOT DARKSSH INSTALLER                \E[0m\n"
+echo -e "\E[44;1;37m             BOT SDSSH INSTALLER                \E[0m\n"
 echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATTENTION \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
 echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mBY YOUR TELEGRAM ACCESS THE FOLLOWING BOT\033[1;37m:\033[0m"
 echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCREATE YOUR BOT \033[1;31mOPTION: \033[1;37m/newbot\033[0m"
